#pragma once

#include <Arduino.h>

#include "AppConfig.h"
#include "FahrenheitSupport.h"
#include "MitsubishiTypes.h"

class MitsubishiProtocol {
public:
    explicit MitsubishiProtocol(HardwareSerial* serial = nullptr)
        : serial_(serial) {
        currentSettings_.reset();
        currentStatus_.reset();
        applyMockDefaults();
    }

    void connect() {
        connected_ = true;
        currentSettings_.connected = true;
    }

    void processInput() {
    }

    void loopPollCycle() {
        currentStatus_.runtimeHours = millis() / 3600000.0f;
    }

    bool isConnected() const {
        return connected_;
    }

    const heatpumpSettings& getCurrentSettings() const {
        return currentSettings_;
    }

    const heatpumpStatus& getCurrentStatus() const {
        return currentStatus_;
    }

    void setDemoConnected(bool connected) {
        connected_ = connected;
        currentSettings_.connected = connected;
    }

    void setDemoRoomTemperature(float value) {
        currentStatus_.roomTemperature = value;
    }

    void applyMockRemoteSettings(const String& power,
                                 const String& mode,
                                 float temperatureF,
                                 const String& fan,
                                 const String& vane,
                                 const String& wideVane) {
        powerStorage_ = power;
        modeStorage_ = mode;
        fanStorage_ = fan;
        vaneStorage_ = vane;
        wideVaneStorage_ = wideVane;

        currentSettings_.temperature = fahrenheitSupport_.setpointFahrenheitToDeviceCelsius(temperatureF);
        currentSettings_.connected = true;
        connected_ = true;

        syncSettingPointers();
        updateDerivedMockStatus();
    }

    float getTargetTemperatureF() const {
        return fahrenheitSupport_.deviceCelsiusToSetpointFahrenheit(currentSettings_.temperature);
    }

    float getRoomTemperatureF() const {
        return fahrenheitSupport_.deviceCelsiusToDisplayFahrenheit(currentStatus_.roomTemperature);
    }

    float getOutsideTemperatureF() const {
        return fahrenheitSupport_.deviceCelsiusToDisplayFahrenheit(currentStatus_.outsideAirTemperature);
    }

    String buildMockConfigPreview() const {
        String config = "# CN105 draft generated by WebUI\n";
        config += "power=" + powerStorage_ + "\n";
        config += "mode=" + modeStorage_ + "\n";
        config += "temperature_f=" + String(getTargetTemperatureF(), 0) + "\n";
        config += "temperature_c_raw=" + String(currentSettings_.temperature, 1) + "\n";
        config += "fan=" + fanStorage_ + "\n";
        config += "vane=" + vaneStorage_ + "\n";
        config += "wideVane=" + wideVaneStorage_ + "\n";
        config += "transport=mock\n";
        config += "status=preview_only\n";
        return config;
    }

private:
    HardwareSerial* serial_;
    heatpumpSettings currentSettings_;
    heatpumpStatus currentStatus_;
    bool connected_ = false;
    String powerStorage_;
    String modeStorage_;
    String fanStorage_;
    String vaneStorage_;
    String wideVaneStorage_;
    FahrenheitSupport fahrenheitSupport_;

    void applyMockDefaults() {
        powerStorage_ = "ON";
        modeStorage_ = "AUTO";
        fanStorage_ = "AUTO";
        vaneStorage_ = "AUTO";
        wideVaneStorage_ = "AIRFLOW CONTROL";

        currentSettings_.temperature = fahrenheitSupport_.setpointFahrenheitToDeviceCelsius(AppConfig::DEFAULT_TARGET_TEMPERATURE_F);
        currentStatus_.roomTemperature = fahrenheitSupport_.setpointFahrenheitToDeviceCelsius(AppConfig::DEFAULT_ROOM_TEMPERATURE_F);
        currentStatus_.outsideAirTemperature = (AppConfig::DEFAULT_OUTSIDE_TEMPERATURE_F - 32.0f) / 1.8f;
        currentStatus_.compressorFrequency = 33.0f;
        currentStatus_.inputPower = 420.0f;
        currentStatus_.kWh = 12.4f;
        currentStatus_.runtimeHours = 87.5f;

        connected_ = true;
        currentSettings_.connected = true;
        syncSettingPointers();
        updateDerivedMockStatus();
    }

    void syncSettingPointers() {
        currentSettings_.power = powerStorage_.c_str();
        currentSettings_.mode = modeStorage_.c_str();
        currentSettings_.fan = fanStorage_.c_str();
        currentSettings_.vane = vaneStorage_.c_str();
        currentSettings_.wideVane = wideVaneStorage_.c_str();
    }

    void updateDerivedMockStatus() {
        bool isOn = powerStorage_ == "ON";
        currentStatus_.operating = isOn;

        if (!isOn) {
            currentStatus_.compressorFrequency = 0.0f;
            currentStatus_.inputPower = 0.0f;
            return;
        }

        if (modeStorage_ == "HEAT") {
            currentStatus_.compressorFrequency = 38.0f;
            currentStatus_.inputPower = 510.0f;
        } else if (modeStorage_ == "COOL" || modeStorage_ == "DRY") {
            currentStatus_.compressorFrequency = 31.0f;
            currentStatus_.inputPower = 360.0f;
        } else if (modeStorage_ == "FAN") {
            currentStatus_.compressorFrequency = 12.0f;
            currentStatus_.inputPower = 85.0f;
        } else {
            currentStatus_.compressorFrequency = 24.0f;
            currentStatus_.inputPower = 250.0f;
        }
    }
};
